[features]
seeds = false

[programs.localnet]
mysolanaapp = "Pkje2SJRri9eRo9tGoU1FV6MJPFBsVmnfEy7HpGrRCd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/sengwee/.config/solana/id.json" # on Linux
# wallet = "/Users/sengwee/.config/solana/id.json" # on MacOS

[scripts]
test = "yarn run mocha -t 1000000 tests/"
